---
name: fish-language-server
description: LSP implementation for the fish shell language
homepage: https://fish-lsp.dev
licenses:
  - MIT
languages:
  - Fish
categories:
  - LSP
source:
  # renovate:datasource=git-refs
  id : pkg:github/ndonfris/fish-lsp@d3c4c7962b73b976db8d5e5bf28c2953024b1ceb
  build:
    run: npm exec 'yarn@1' install
bin:
  fish-language-server: node:bin/fish-lsp
