---
name: fish-language-server
description: LSP implementation for the fish shell language
homepage: https://fish-lsp.dev
licenses:
  - MIT
languages:
  - Fish
categories:
  - LSP
source:
  # renovate:datasource=git-refs
  id: pkg:github/ndonfris/fish-lsp@df7b1f7e093ad06f7e083ba557ae4c71850ab0d7
  build:
    run: npm exec 'yarn@1' install
bin:
  fish-language-server: node:bin/fish-lsp
